apiVersion: apps/v1
kind: Deployment
metadata:
  name: blahblah
  namespace: default
spec:
  template:
    metadata:
      namespace: default
    spec:
      containers:
        - imagePullPolicy: IfNotPresent
          name: container-0
          securityContext:
            runAsNonRoot: false
            readOnlyRootFilesystem: false
            privileged: false
            allowPrivilegeEscalation: false
          _init: false
          image: alpine
          stdin: false
          stdinOnce: false
          command:
            - sleep
          tty: false
          args:
            - '300'
      restartPolicy: Always
  replicas: 1
